import re

import pandas as pd

import app as app_module
from app import AI_SUMMARY_CACHE, DATAFRAME_CACHE, app
from data_analysis.ai import engine as ai_engine
from data_analysis.ai import service as ai_service


class _Resp:
    def __init__(self, text: str):
        self.text = text


def test_summary_simple_fallback_keeps_model_marker(monkeypatch):
    responses = iter([_Resp(""), _Resp("<p>Fallback summary</p>")])

    monkeypatch.setattr(ai_engine, "ensure_ai_ready", lambda **_kwargs: True)
    monkeypatch.setattr(ai_engine, "_call_gemini", lambda *_args, **_kwargs: next(responses))
    monkeypatch.setattr(ai_engine, "_extract_text_from_gemini_response", lambda resp, **_kwargs: resp.text)
    monkeypatch.setattr(ai_engine, "_diagnose_gemini_response", lambda *_args, **_kwargs: "")
    monkeypatch.setattr(ai_engine, "_get_finish_reason", lambda *_args, **_kwargs: None)
    monkeypatch.setattr(ai_engine, "CURRENT_MODEL_NAME", "models/gemini-3.0-flash")

    out = ai_service.get_ai_summary_with_file(
        pd.DataFrame({"x": [1, 2]}),
        extra_context="ctx",
        sanitize_ai_html_fn=lambda s: s,
    )

    assert "Fallback summary" in out
    assert "<!-- model:models/gemini-3.0-flash -->" in out


def test_qna_response_keeps_model_marker(monkeypatch):
    monkeypatch.setattr(ai_engine, "ensure_ai_ready", lambda **_kwargs: True)
    monkeypatch.setattr(ai_engine, "_call_gemini", lambda *_args, **_kwargs: _Resp("<p>Answer</p>"))
    monkeypatch.setattr(ai_engine, "_extract_text_from_gemini_response", lambda resp, **_kwargs: resp.text)
    monkeypatch.setattr(ai_engine, "_get_finish_reason", lambda *_args, **_kwargs: None)
    monkeypatch.setattr(ai_engine, "CURRENT_MODEL_NAME", "models/gemini-2.5-flash-lite")

    out = ai_service.get_ai_answer_with_file(
        pd.DataFrame({"x": [1, 2]}),
        "What changed?",
        sanitize_ai_html_fn=lambda s: s,
    )

    assert "<p>Answer</p>" in out
    assert "<!-- model:models/gemini-2.5-flash-lite -->" in out


def test_overview_post_keeps_distinct_summary_and_answer_models(monkeypatch):
    filename = "a" * 40 + ".csv"
    DATAFRAME_CACHE.set(filename, pd.DataFrame({"value": [1.0, 2.0, 3.0]}))
    AI_SUMMARY_CACHE[filename] = "<p>Summary</p><!-- model:models/gemini-3.0-flash -->"

    monkeypatch.setattr(
        app_module,
        "get_ai_answer_with_file",
        lambda *_args, **_kwargs: "<p>Answer</p><!-- model:models/gemini-2.5-flash-lite -->",
    )

    with app.test_client() as client:
        response = client.post(
            f"/analyze/{filename}?view=overview",
            data={"question": "Explain this"},
        )

    text = response.data.decode("utf-8", errors="replace")
    assert response.status_code == 200
    assert "Generated by gemini-3.0-flash" in text
    assert "Generated by gemini-2.5-flash-lite" in text


def test_overview_post_hides_summary_attribution_on_quota_error(monkeypatch):
    filename = "b" * 40 + ".csv"
    DATAFRAME_CACHE.set(filename, pd.DataFrame({"value": [1.0, 2.0, 3.0]}))
    AI_SUMMARY_CACHE[filename] = "<p>AI summary unavailable: 429 You exceeded your current quota.</p>"

    monkeypatch.setattr(
        app_module,
        "get_ai_answer_with_file",
        lambda *_args, **_kwargs: "<p>Answer</p><!-- model:models/gemini-2.5-flash-lite -->",
    )

    with app.test_client() as client:
        response = client.post(
            f"/analyze/{filename}?view=overview",
            data={"question": "Explain this"},
        )

    text = response.data.decode("utf-8", errors="replace")
    assert response.status_code == 200
    assert "AI summary unavailable: 429" in text
    assert re.search(r'id="ai-summary-attribution"\s+hidden', text) is not None
    assert "Generated by gemini-2.5-flash-lite" in text


def test_overview_post_summary_without_marker_keeps_default_summary_model(monkeypatch):
    filename = "c" * 40 + ".csv"
    DATAFRAME_CACHE.set(filename, pd.DataFrame({"value": [1.0, 2.0, 3.0]}))
    AI_SUMMARY_CACHE[filename] = "<p>Summary without marker</p>"

    monkeypatch.setattr(app_module, "CURRENT_MODEL_NAME", "models/gemini-2.5-flash-lite")
    monkeypatch.setattr(
        app_module,
        "get_ai_answer_with_file",
        lambda *_args, **_kwargs: "<p>Answer</p><!-- model:models/gemini-2.5-flash-lite -->",
    )

    with app.test_client() as client:
        response = client.post(
            f"/analyze/{filename}?view=overview",
            data={"question": "Explain this"},
        )

    text = response.data.decode("utf-8", errors="replace")
    assert response.status_code == 200
    expected_summary_model = str(app_module.DEFAULT_AI_MODEL).replace("models/", "", 1)
    assert f"Generated by {expected_summary_model}" in text
    assert "Generated by gemini-2.5-flash-lite" in text
